Default: &defaults
  database: randumb.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: randumb_test.sqlite3
  <<: *defaults

Staging:
  database: randumb_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: randumb_production.sqlite3
  poolsize: 100
  <<: *defaults
